package.json
src/server/api/index.ts
src/server/checker/CheckerController.ts
src/server/checker/index.ts
src/server/index.ts

As a pro-active effort to provide some backend facilities to the dev team,
Refactor api into its own module, then inject a controller
that wraps around a stubbed checker repository
- Create a module that acts as a factory for the Express router
that embodies the API, taking in an options object for dependencies
- Mount the API at `/api/v1`
- Create a CheckerController to act as the Express controller for
`/c` endpoints.
- Let this wrap around an object that just keys strings to
the checker templates

feat(api): stub CRUD for checker template

---

package-lock.json
package.json
src/client/components/Checker.tsx
src/server/api/index.ts
src/server/checker/CheckerController.ts
src/server/checker/CheckerService.ts
src/server/checker/index.ts
src/server/index.ts
src/server/models/Checker.ts
src/server/models/index.ts
src/types/checker.d.ts

The current backend is not a realistic depiction of what may be the final production service
Flesh out the backend further by introducing a Sequelize model
and necessary encapsulations to persist/retrieve checker instances.
Allow the user to specify the primary key, enforcing uniqueness. This
is in-line with how short urls are unique in GoGovSg and usable
as PKs; in a similar vein, we want urls to checkers to be memorable
to humans.
- Add sequelize, sqlite
- Rename the Config interface in types/checker to Checker
- Add associated Sequelize model
- Create a service wrapper around Checker model, injecting all this
into the controller
- Rewrite the controller to accommodate Sequelize (via the service)

feat: add sequelize backed by sqlite

---

src/client/components/Checker.tsx
src/client/core/__test__/evaluator.spec.ts
src/client/core/evaluator.ts

This PR renames two evaluator functions described in https://github.com/opengovsg/checkfirst/pull/20#discussion_r557253157 and https://github.com/opengovsg/checkfirst/pull/20#discussion_r557250266 for clarity.

style: rename evaluation functions

---

src/server/api/index.ts
src/server/checker/CheckerController.ts
src/server/checker/CheckerService.ts
src/server/models/Checker.ts

The backend for the checker infra was implemented in a hurry, and in need of a cleanup
- remove eslint suppression for `service.retrieve()` return type now that `ModelOf` type corrected
- replace `res.send()` calls with `res.json()` in the controller
- stubplement the listing of checkers in Sequelize for the user dashboard on login
- correct the sequelize model fields so that they line up with `types/checker` declared properties

refactor(checker): cleanup

---

src/client/contexts/AuthContext.tsx
src/client/hooks/use-local-storage.ts
src/client/pages/Landing.tsx
src/client/services/AuthService.ts
src/server/api/index.ts
src/server/auth/AuthController.ts
src/server/auth/__test__/AuthController.spec.ts
src/types/server/express-session.d.ts

The frontend needs to logout and figure out if it has been authenticated 
- implement `/whoami` and `/logout`, which do as their names imply
- use declaration merging to add a user property to `req.session`
- switch `isAuthenticated` from a state hook to a local storage hook
derived from [1]
- implement `AuthService.logout()`, `AuthContext.logout()`
- hook Logout button to `AuthContext.logout()`, add link to Projects
[1] - https://usehooks-typescript.com/react-hook/use-local-storage
The author thanks @karrui for the hint on using local storage within
a React hook

feat(auth): implement /logout , /whoami

---

src/client/components/LogoutButton.tsx
src/client/components/PrivateRoute.tsx
src/client/components/builder/Navbar.tsx
src/client/components/projects/Navbar.tsx
src/client/components/projects/index.tsx
src/client/contexts/AuthContext.tsx
src/client/pages/Landing.tsx
src/client/pages/Projects.tsx

The projects page has to be fleshed out to allow users to create and manage checkers. 
This PR seeks to put in place a navigation bar. It also changes AuthContext to expose
more information, information that the user will expect to see on successful login.
- Copy the navbar from builder, and restructure it to fit wireframe
- Create a common LogoutButton and use in projects and builder navbars,
complete with functionality to logout and redirect to home page
- Deliberately avoid the tab interface proposed for the dashboard,
as we are unlikely to have settings, leaving just one panel

feat(projects): implement navbar

---

package-lock.json
package.json
src/client/components/builder/CheckboxField.tsx
src/client/components/builder/NumericField.tsx
src/client/components/builder/QuestionField.tsx
src/client/components/builder/QuestionsTab.tsx
src/client/components/builder/RadioField.tsx
src/client/components/builder/TitleField.tsx
src/client/components/fields/CheckboxField.tsx
src/client/components/fields/RadioField.tsx
src/client/contexts/CheckerContext.tsx
src/client/contexts/__test__/CheckerContext.spec.ts
src/client/pages/Checker.tsx
src/types/builder.d.ts
src/types/checker.d.ts
src/util/enums.ts

This PR adds the reducer functionality to the checker builder as well as the relevant tests. 
Specifically, the reducer accepts 4 actions (`Add`, `Remove`, `Update`, and `Reorder`) and applies these reducer actions to any of the 4 config arrays (`fields`, `operations`, `displays`, `constants`).

feat: add reducer to Builder

---

src/server/checker/CheckerController.ts
src/server/checker/CheckerService.ts
src/server/checker/__test__/CheckerController.spec.ts
src/server/checker/__test__/CheckerService.spec.ts
src/types/checker.d.ts

Checkers are freely accessible by all because there is no user authorization checks actually being done
- Ensure the user can update/delete the checker
- Ensure the user lists only the checkers he/she has access to
- When retrieving a checker, if anonymous or user with no access to
checker, return the checker without user information
- Similarly, if user is retrieving his/her own checker, add user
information

feat(checker): authenticate user before operations

---

src/client/components/builder/Navbar.tsx
src/client/contexts/CheckerContext.tsx

https://user-images.githubusercontent.com/10572368/105811464-a4173300-5fe7-11eb-907f-97c8d392df68.mov
We currently do not prompt when the user has unsaved changes 
- When loading checker from backend, keep a copy of that config
- Compare copy against current state of checker config, and mark
if there are changes
- Use that to enable/disable the save button
- If `isChanged`, warn the user about discarding changes, navigating
back to `/dashboard` on confirmation
- Change title placeholder in navbar from button to text

feat(builder): warn user with modal if unsaved changes

---

src/client/components/builder/LogicTab.tsx
src/client/components/builder/QuestionsTab.tsx

This PR fixes a bug where the numbering of fields and operations would restart upon reloading the page. We now look through the existing items in fields/operations to determine the appropriate index to use.
This PR also fixes a minor bug involving the reordering of operations when moving down.

fix: prevent restart of field numbering when reloading page

---

src/client/components/Checker.tsx

Currently, the `NumericField` value type in the Checker object is `string`, when it should actually be `number`. This results in admin users having to specify string comparisons in the IF/ELSE Logic builder statements (as shown in the image below).
The solution is to iterate through all `inputs` provided when the citizen user hits the submit button and casting the `NumericField` value as `number`.
I attempted to explore alternative solutions - such as by attempting to set the underlying `type` of the HTML Input element to `number` via ChakraUI. However, ChakraUI's `NumberInput` does not allow us to set the underlying Input `type` directly, and the `NumberInput`'s `value` and `onChange` type is `number | string` ([source](https://github.com/chakra-ui/chakra-ui/issues/278)).

fix: ensure that NumericField values type number instead of string

---

src/client/components/Checker.tsx

This PR applies a transformation step to the field input values for the Radio and Checkbox fields.
**Radio**
Currently, the input value of the radio field is the `value` (index) of the selected option, e.g. `"0"`. The new change applies a transformation to set the input value as the `label` of the selected option label, e.g. `"Option A"`.
**Checkbox**
Currently, the input value of the checkbox field is an array of selected option `value`, e.g. `["0", "1"]`. The new change a transformation to set the input value as a serialized string representing the array of selected option labels, e.g. `"[\"Option A\",\"Option B\"]"`

fix: return option labels instead of values for Radio and Checkbox fields

---

src/server/bootstrap/sequelize.ts
src/server/checker/CheckerService.ts
src/server/config.ts

When run on local machine, sqlite needs to persist data between runs
By default, persist sqlite data to disk, path specified by
`SQLITE_PATH`. If that path is an empty string, assume storage
is in-memory
- Declare a new env var, `SQLITE_PATH`, default `/tmp/checkfirst.db`
- When creating a Sequelize instance, for the sqlite dialect, if
an empty `SQLITE_PATH` is given, assume that in-memory storage
is desired (ie, the sequelize default)
- Because sqlite does not handle transaction locking very well (eg,
a txn cannot write to a table if it the same txn has locked it for
reading), detect if sequelize is using sqlite backed by a file,
and avoid using a transaction if so
- Take the trouble to extend cookie age to 4 hours
**New environment variables**:
- `SQLITE_PATH` : the file to persist …

feat(sqlite): persist to file

---

src/client/components/builder/BuilderField.tsx
src/client/components/builder/LogicTab.tsx
src/client/components/builder/QuestionsTab.tsx

This PR fixes a minor bug involving duplicate ids when duplicating fields and operations.

fix: add unique id logic when duplication fields/operations

---

src/client/components/builder/logic/ConditionalResult.tsx

When if expression if empty, the application crashes because the first `and` or `or` condition gets collapsed to a function call (e.g. `and(2 == 2)` instead of `1 == 1 and (2 == 2)`)
Closes [insert issue #]
**Bug Fixes**:
- Relax the regex expression to allow for an optional space between the `and` and `or` operators to support both forms. This is a stop-gap fix that might need to be re-looked in the future.

fix: parsing error that causes application to crash

---

src/client/components/builder/FloatingToolbar.tsx
src/client/components/builder/LogicTab.tsx
src/client/components/builder/logic/MapResult.tsx
src/client/components/builder/logic/index.ts
src/types/checker.d.ts

This PR adds the MapResult component to the Logic Tab.
**Active/focused**
**Active/focused with active selector**
**Inactive/unfocused**

feat: add map result to the logic tab

---

src/client/components/Checker.tsx

Current Radio field implementation assumes that the `value` is equals to the index in the `options` array. However, this might not be true if the length of the `options` array changes. 
To reproduce the error:
1. Create a Radio field in the Question Tab
2. Delete the first option
3. Attempt to submit form in the Preview tab
4. An error with the message `Cannot read property 'label' of undefined` should be logged in the console
**Bug Fixes**:
- Look up the corresponding option based on `value` when mapping user input to value for Radio fields.

fix: lookup option by value instead of index for radio field

---

src/server/api/index.ts

This PR adds a GET `/ping` endpoint that we can use to check for uptime.

feat: add /ping endpoint for uptime check

---

src/client/contexts/AuthContext.tsx

`useLocalStorage()` uses `JSON.parse()` to retrieve previously
stringified values from localStorage. This is problematic as
`JSON.stringify()` serializes `undefined` to the string "undefined",
which it is then unable to parse, throwing a spurious warning
To mitigate this, change the type of `[user, setUser]` to be
`User | null`, so that we are forced to avoid `undefined`. This also
better lines up with what is returned by `/auth/whoami` in the backend.

fix(auth): change user localStorage to User | null

---

src/client/components/Checker.tsx

- removes the chakra generated css for 'strech'
- no noticeable changes since the default for flex align-items is stretch

fix: 'strech' typo in checker result align prop

---

src/server/config.ts

By default, we want CSP violations to be stopped. Hence change in default `convict` value.

fix: csp only report violations default to false

---

src/server/auth/AuthService.ts
src/server/auth/__test__/AuthService.spec.ts

Users prefer seeing time left for their OTP in minutes.
**Improvements**:
- Format time left for OTP as minutes (rounded down to nearest minute)
- Login and check that email states OTP in minutes

chore: express time left for otp in minutes

---

src/client/components/dashboard/CreateNewModal.tsx

Closes #245 
_How did you solve the problem?_
**Improvements**:
- Allow user to modify checker title and description when duplicating checker
**Bug Fixes**:
- Generate a new `uuid` when duplicating checker
- Create a checker with title and description 
- Click duplicate and ensure that the form is pre-populated with values for title and description based on the original checker
- Confirm duplication and checker should be successfully created

fix: generate new uuid when duplicating checker

---

src/client/components/builder/Navbar.tsx
src/client/hooks/use-local-storage.ts

Closes #241 
- non-ascii quotation marks cause css in sample iframe tag in the embed modal to fail
- removed other instances of non-ascii quotes
Possible extension: add ESLint plugin: https://github.com/personaljs/eslint-plugin-ascii though i think this problem isn't significant enough to warrant the extra dependency

fix: use ascii quotation marks

---

src/client/components/Checker.tsx
src/client/components/builder/BuilderField.tsx
src/client/components/builder/QuestionsTab.tsx
src/client/components/builder/questions/DropdownField.tsx
src/client/components/builder/questions/index.ts
src/client/components/fields/DropdownField.tsx
src/client/components/fields/index.ts
src/server/checker/CheckerSchema.ts
src/types/checker.d.ts

RadioField tends to be unwieldy for situations where more than 5 options are needed
Create DropdownField, using textarea as input
- copy RadioField and add relevant entries across the builder and public views
- ditch the radio buttons borrowed from RadioField in favour of chakra's Select control
- use a textarea to accept DropdownField options

feat(builder): create DropdownField

---

src/client/contexts/CheckerContext.tsx

By default, react-query fetches the last saved state of the checker
when the user refocuses the window (eg, by clicking on another browser
tab then returning to CheckFirst). This decimates any unsaved changes
that the user might have had.
Fix this by explicitly specifying no fetching on window refocus

fix(builder): do not fetch checker on window refocus

---

.github/workflows/ci.yml
src/server/auth/AuthService.ts
src/server/auth/__test__/AuthService.spec.ts
src/server/bootstrap/index.ts
src/server/config.ts

Closes #290 
Specify exactly which app host is sending OTP mails, given as env var
- Declare a new convict config field - `appHost` - that specifies the
application host name for the running backend process
- Specify `APP_HOST` in GitHub Workflows for injection into application
- Inject `appHost` into AuthService for use in OTP mails
**New environment variables**:
- `APP_HOST` : The fully-qualified domain name of the application

feat(otp): include app host when sending OTP mail

---

src/client/tsconfig.json

This PR sets the `experimentalDecorators` flag to `true` in the client's `tsconfig.json` to suppress the following compiler errors. 
Note: We attempted to use the `exclude` parameter: `exclude: ['../server']` to no avail.

chore: add experimentalDecorators config in client

---

src/client/components/builder/BuilderField.tsx

Title cards should not have duplicate or delete options. All checkers should have one and only one title.
Closes #291 
**Bug Fixes**:
- Skip rendering of duplicate and delete options if it is a title card

fix(builder): disable duplicate and delete on title card

---

src/client/components/builder/BuilderField.tsx

Closes #287 
- Make deep copy of field through `JSON.stringify()` and `JSON.parse()`
- DRY `handleDuplicate()` out by limiting repeated code to the creation
of `payload`. Duplicate blocks are still needed so that we match the
correct ConfigArrayEnum to the correct type of `element`

fix(builder): ensure deep copy of field, remove code repetition

---

src/server/checker/CheckerService.ts
src/server/checker/__test__/CheckerService.spec.ts
src/server/database/models/Checker.ts
src/server/database/models/User.ts
src/server/database/models/UserToChecker.ts

This PR fixes the jankiness https://github.com/opengovsg/checkfirst/pull/285 that is:
> I had to do this strange type assertion chain here:
`const checkerInstance = await this.CheckerModel.create((checker as any) as CheckerModel, options)`
Turns out I was using the `sequelize-typescript` v1 API for defining a model whereas our version is ^2.1.0:
```
export class Checker extends Model<Checker> {
```
Whereas the new `sequelize-typescript` v2 API for defining a model is:
```
export class Checker extends Model {
```

fix: use sequelize-typescript v2 API for defining model class

---

.github/workflows/ci.yml
package-lock.json
package.json
serverless.yml
src/client/App.tsx
src/server/bootstrap/index.ts
src/server/config.ts
webpack.config.js

- use sentry express integration
- set user from session user
**New environment variables**:
- `BACKEND_SENTRY_DSN`
- `CSP_REPORT_URI`: wasn't previously linked up in `serverless.yml` and `ci.yml` for the CSP PR
**New dependencies**:
- `@sentry/node`
- `@sentry/tracing`
Add a route that throws an error: https://docs.sentry.io/platforms/node/guides/express/. Then ping that endpoint by navigating to it on browser eg. `localhost:3000` or using postman.
```
app.get("/debug-sentry", function mainHandler(req, res) {
throw new Error("My first Sentry error!");
});
```
NOTE: an error thrown in a async function won't be caught by sentry error handler
TODO: 
- fix `sentrySessionMiddleware` to add user info when error occurs
- investigate further as to why async functions are not caught by sentry

feat: add backend sentry

---

serverless.yml
src/server/database/config/config.ts

- Database hostname was missing in the connection config
- CSP headers env var for static lambda were missing

fix: missing db hostname and added CSP env var to static lambda

---

src/server/config.ts

Fixes https://github.com/opengovsg/checkfirst/issues/317

fix: set default cookieMaxAge to 24h

---

src/client/components/fields/RadioField.tsx

Checkers currently render radio button groups with the first value selected,
potentially leading the user
To avoid leading the user of a checker, do not set the form radio
option to any default value

fix(radio): avoid selecting default value
